### ISSUE TITLE
Suggestion on Angular Schematics usage and Angular Style Guide

### ISSUE THREAD

**Issue by doggy8088** [andriy101/primeng-schematics#2]
Your PrimeNG Schematics is really useful.  Here are some suggestions for you:

1. You might support the following usage as well because it's common usage for generating a component.

    ```
    ng g primeng-schematics:primeng-menubar <component-name>
    ```

2. For the default selector of a component, the Angular Style Guide suggestion using `app-componentname` as a selector.  The `app-` is also defined in `angular.json`. ( `prefix` )  You might be able to read the `prefix` setting on `angular.json` file.

3. The Angular CLI contains a workspace setting by default.  Which mean you can provide a `--project` as an option on your PrimeNG schematics.  That will be awesome for aligement with Angular CLI use case.

Thanks for your contribution. 👍

**Comment by andriy101** [comment]
All three suggestions done in V7.X.X
